# Rules based on default swiftlint.

included: # paths to include during linting. `--path` is ignored if present.
  - "ios-row"
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - opening_brace
  - function_parameter_count
  - multiple_closures_with_trailing_closure
  - trailing_whitespace
  - large_tuple
  - type_name
  - members_naming_id
  - nesting
opt_in_rules: # some rules are only opt-in
  - empty_count
  - implicitly_unwrapped_optional
  - force_unwrapping
  - fallthrough
  - multiline_parameters
  - redundant_type_annotation
  - redundant_nil_coalescing
  - identical_operands
  - prohibited_super_call
  - overridden_super_call
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - closure_body_length
  - first_where
  - empty_count - Prefer checking isEmpty over comparing count to zero.
  - empty_string - Prefer checking isEmpty over comparing string to an empty string literal.
  - control_statement - if,for,while,do,catch statements shouldn't wrap their conditionals or arguments in parentheses.
  - statement_position - Else and catch should be on the same line, one space after the previous declaration.
  - generic_type_name - Generic type name should only contain alphanumeric characters, start with an uppercase character and span between 1 and 20 characters in length.
  - contains_over_first_not_nil - Prefer contains over first(where:) != nil
  - discouraged_object_literal - Prefer initializers over object literals.
  - fatal_error_message - A fatalError call should have a message.
  - first_where - Prefer using .first(where:) over .filter { }.first in collections.
  - discouraged_optional_collection - Prefer empty collection over optional collection.
  - quick_discouraged_focused_test - Discouraged focused test. Other tests won't run while this one is focused.
  - quick_discouraged_pending_test - Discouraged pending test. This test won't run while it's marked as pending.
  - syntactic_sugar - Shorthand syntactic sugar should be used, i.e. [Int] instead of Array.
  - void_return - Prefer -> Void over -> ()
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
type_body_length:
  warning: 200
  error: 450
line_length:
  warning: 240
  error: 620
  ignores_function_declarations: false
  ignores_urls: true
  ignores_interpolated_strings: true
file_length:
  warning: 500
  error: 750
indentation: 2
force_cast: warning
force_try: warning
