setup_travis

REQUIRED_XCODE_VERSION = '11.6'
default_platform :ios

fastlane_require 'behave'
fastlane_version '2.127.2'

platform :ios do
  before_all do
    verify_xcode_version(version: REQUIRED_XCODE_VERSION)
    ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '120'
  end
  
  desc 'Runs all the tests for ios-row'
  lane :test_all do
    reset_simulators
    clear_derived_data
    test_ios_row
    reset_simulators
  end
  
  private_lane :verify_xcode_version do
    ensure_xcode_version(version: REQUIRED_XCODE_VERSION)
  end
  
  desc 'This kills the Simulator process, and reset all simulators with Snapshot'
  lane :reset_simulators do
    reset_simulator_contents
  end
  
  desc 'Runs all the tests for ios-row'
  lane :test_ios_row do
    scan(scheme: 'ios-row', devices: ['iPhone 8'], skip_build: true, clean: false)
    sh 'mv test_output/report.junit test_output/ios-row.xml'
  end
  
  desc 'Run all the tests for ios-row + Coverage'
  lane :test_coverage_ios_row do
    test_ios_row
    xcov(scheme: 'ios-row', skip_slack: true, slack_url: '', slack_channel: 'xcovreport', slack_message: 'ios_row test report: Commit ' + last_git_commit[:commit_hash] + ' by ' + last_git_commit[:author], minimum_coverage_percentage: 2.1)
  end
end
