platform :ios, '12.0'

use_frameworks!
inhibit_all_warnings!

workspace 'BetwayROW'

def projectPods
  pod 'SwiftLint'
end

def unitTestPods
end

def uiTestPods
end

target 'BetwayROW' do
  projectPods

  # Pods for BetwayROW

  target 'BetwayROWTests' do
    inherit! :search_paths
    unitTestPods
  end

  target 'BetwayROWUITests' do
    inherit! :search_paths
    unitTestPods
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
